import Foundation

/// Decides whether a clipboard change gets captured (F1, F9). Pure logic, shared by every platform watcher.
public enum CaptureFilter {
    /// nspasteboard.org markers that password managers and other apps put next to secrets.
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    /// 1Password's own marker type.
    public static let onePasswordType = "com.agilebits.onepassword"
    /// Written by ClipSync next to text it puts on the pasteboard, so copying from history isn't recaptured.
    public static let ownMarkerType = "dev.jazz.clipsync.own"

    /// Any of these types on the pasteboard means "don't capture".
    public static let concealedTypes: Set<String> = [concealedType, transientType, autoGeneratedType, onePasswordType]

    /// Text larger than this (UTF-8 bytes) is skipped. Note the relay caps one op at 256 KB of ciphertext,
    /// so text between that and this cap is still refused by SyncEngine (`AppMessage.tooLarge`).
    public static let maxBytes = 1_048_576

    public enum Decision: Equatable, Sendable {
        case capture(String)
        /// A password manager or similar marked it concealed or transient (F9).
        case concealed
        /// ClipSync wrote it (a copy from history).
        case ownWrite
        /// No text, or only whitespace.
        case empty
        case tooLarge
    }

    public static func decide(types: [String], text: String?) -> Decision {
        if types.contains(ownMarkerType) { return .ownWrite }
        if types.contains(where: concealedTypes.contains) { return .concealed }
        guard let text, !text.allSatisfy(\.isWhitespace) else { return .empty }
        if text.utf8.count > maxBytes { return .tooLarge }
        return .capture(text)
    }
}

/// What a platform reads off its clipboard.
public struct PasteboardContents: Equatable, Sendable {
    /// Type identifiers present (UTIs on Apple).
    public var types: [String]
    /// The plain text, if any.
    public var text: String?

    public init(types: [String], text: String?) {
        self.types = types
        self.text = text
    }

    /// True when a password manager marked the contents concealed or transient (F9).
    public var isConcealed: Bool { types.contains(where: CaptureFilter.concealedTypes.contains) }
}

/// Puts text on the platform clipboard (NSPasteboard, UIPasteboard). Implementations also add
/// `CaptureFilter.ownMarkerType` where the platform watches the clipboard, so the write isn't recaptured.
@MainActor
public protocol PasteboardWriter: AnyObject {
    func write(text: String)
}

/// Reads the platform clipboard.
@MainActor
public protocol PasteboardReader: AnyObject {
    /// Bumps on every clipboard change (NSPasteboard.changeCount). Cheap to read.
    var changeCount: Int { get }
    func read() -> PasteboardContents
}

/// The watcher's decision logic, minus the timer: the platform calls `poll()` on its own schedule.
@MainActor
public final class ClipboardPoller {
    public var isPaused: Bool
    private let reader: any PasteboardReader
    private var lastChangeCount: Int

    /// Starts from the clipboard's current state, so whatever was copied before launch isn't captured.
    public init(reader: any PasteboardReader, isPaused: Bool = false) {
        self.reader = reader
        self.isPaused = isPaused
        self.lastChangeCount = reader.changeCount
    }

    /// Returns text to capture when the clipboard changed since the last poll and the filter allows it.
    /// While paused, changes are noted but dropped, so resuming doesn't capture something copied during the pause.
    public func poll() -> String? {
        let count = reader.changeCount
        guard count != lastChangeCount else { return nil }
        lastChangeCount = count
        guard !isPaused else { return nil }
        let contents = reader.read()
        if case .capture(let text) = CaptureFilter.decide(types: contents.types, text: contents.text) {
            return text
        }
        return nil
    }
}
