import ClipCrypto
import ClipStore
import ClipSync
import Foundation
import XCTest
@testable import ClipAppCore

final class CaptureFilterTests: XCTestCase {
    let text = "public.utf8-plain-text"

    func testPlainTextIsCaptured() {
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: "hello"), .capture("hello"))
    }

    func testConcealedAndTransientMarkersAreSkipped() {
        for marker in [
            "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        ] {
            XCTAssertEqual(CaptureFilter.decide(types: [text, marker], text: "hunter2"), .concealed, marker)
            XCTAssertTrue(PasteboardContents(types: [marker, text], text: "hunter2").isConcealed, marker)
        }
        XCTAssertFalse(PasteboardContents(types: [text], text: "x").isConcealed)
    }

    func testOwnWritesAreSkipped() {
        XCTAssertEqual(CaptureFilter.decide(types: [text, CaptureFilter.ownMarkerType], text: "from history"), .ownWrite)
    }

    func testEmptyAndWhitespaceAreSkipped() {
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: nil), .empty)
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: ""), .empty)
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: " \n\t "), .empty)
        XCTAssertEqual(CaptureFilter.decide(types: ["public.png"], text: nil), .empty)
    }

    func testOneMegabyteCap() {
        let atCap = String(repeating: "a", count: CaptureFilter.maxBytes)
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: atCap), .capture(atCap))
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: atCap + "a"), .tooLarge)
        // Counted in UTF-8 bytes, not characters.
        let emoji = String(repeating: "😀", count: CaptureFilter.maxBytes / 4 + 1)
        XCTAssertEqual(CaptureFilter.decide(types: [text], text: emoji), .tooLarge)
    }
}

// Tests here are async on purpose: Linux XCTest discovery crashes casting a synchronous
// @MainActor test method to () -> () ("Could not cast value of type ...").
@MainActor
final class ClipboardPollerTests: XCTestCase {
    func testCapturesOnlyNewAllowedChanges() async {
        let pasteboard = FakePasteboard()
        pasteboard.set(types: ["public.utf8-plain-text"], text: "before launch")
        let poller = ClipboardPoller(reader: pasteboard)

        XCTAssertNil(poller.poll(), "what was there at launch isn't captured")

        pasteboard.set(types: ["public.utf8-plain-text"], text: "new copy")
        XCTAssertEqual(poller.poll(), "new copy")
        XCTAssertNil(poller.poll(), "no change, no capture")

        pasteboard.set(types: ["public.utf8-plain-text", CaptureFilter.concealedType], text: "secret")
        XCTAssertNil(poller.poll())

        pasteboard.write(text: "copied from history")
        XCTAssertNil(poller.poll(), "own writes aren't recaptured")
    }

    func testPauseDropsChangesMadeWhilePaused() async {
        let pasteboard = FakePasteboard()
        let poller = ClipboardPoller(reader: pasteboard, isPaused: true)
        pasteboard.set(types: ["public.utf8-plain-text"], text: "during pause")
        XCTAssertNil(poller.poll())
        poller.isPaused = false
        XCTAssertNil(poller.poll(), "resuming doesn't capture what was copied during the pause")
        pasteboard.set(types: ["public.utf8-plain-text"], text: "after")
        XCTAssertEqual(poller.poll(), "after")
    }
}

final class AppMessageTests: XCTestCase {
    func testErrorsMapToMessages() {
        let cases: [(any Error, AppMessage)] = [
            (SyncError.emptyText, .emptyText),
            (SyncError.opTooLarge(bytes: 300_000), .tooLarge),
            (SyncError.invalidPairingCode, .invalidCode),
            (SyncError.pairingNotFound, .codeNotFound),
            (SyncError.pairingDecryptionFailed, .codeMismatch),
            (SyncError.missingSeq, .server),
            (TransportError.network("timed out"), .serverUnreachable),
            (TransportError.unauthorized, .unauthorized),
            (TransportError.rateLimited, .rateLimited),
            (TransportError.payloadTooLarge, .tooLarge),
            (TransportError.server(502), .server),
            (TransportError.decoding, .server),
            (AppError.invalidServerURL, .invalidServer),
            (AppError.notSetUp, .notSetUp),
            (AppError.keyStore("errSecInteractionNotAllowed"), .keychain),
            (StoreError(code: 10, message: "disk I/O error"), .storage),
            (CryptoError.decryptionFailed, .unknown),
            (CancellationError(), .unknown),
        ]
        for (error, expected) in cases {
            XCTAssertEqual(AppMessage(error), expected, "\(error)")
        }
    }

    func testEveryMessageHasCopyWithoutRawErrorText() {
        for message in AppMessage.allCases {
            XCTAssertFalse(message.text.isEmpty, message.rawValue)
            XCTAssertFalse(message.text.contains("Error"), message.rawValue)
        }
    }

    func testServerURLParsing() {
        XCTAssertEqual(AppConfig.parseServerURL(" http://relay:8080 ")?.absoluteString, "http://relay:8080")
        XCTAssertEqual(AppConfig.parseServerURL("relay.tail1234.ts.net:8080")?.absoluteString,
                       "http://relay.tail1234.ts.net:8080")
        XCTAssertEqual(AppConfig.parseServerURL("https://relay")?.absoluteString, "https://relay")
        XCTAssertNil(AppConfig.parseServerURL(""))
        XCTAssertNil(AppConfig.parseServerURL("ftp://relay"))
        XCTAssertNil(AppConfig.parseServerURL("http://"))
    }

    func testConfigDecodesWithoutCapturePaused() throws {
        let json = #"{"serverURL":"http://relay:8080","deviceID":"\#(UUID().uuidString)","deviceName":"Mac"}"#
        let config = try JSONDecoder().decode(AppConfig.self, from: Data(json.utf8))
        XCTAssertFalse(config.capturePaused)
    }
}
